## Assignment 8(DA-3 Big Mart Sales Analysis)
##### Name: Rohit Kulkarni
##### Roll No: 41346
##### Batch: R3

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline


In [3]:
train = pd.read_csv("Train.csv")
test = pd.read_csv("Test.csv")

In [4]:
#Combine test and train into one file
train['source']='train'
test['source']='test'
data = pd.concat([train, test],ignore_index=True)
print(train.shape, test.shape, data.shape)

(8523, 13) (5681, 12) (14204, 13)


In [5]:
data.head()

Item_Identifier  Item_Weight  ... Item_Outlet_Sales  source
0           FDA15         9.30  ...         3735.1380   train
1           DRC01         5.92  ...          443.4228   train
2           FDN15        17.50  ...         2097.2700   train
3           FDX07        19.20  ...          732.3800   train
4           NCD19         8.93  ...          994.7052   train

[5 rows x 13 columns]

In [6]:
#Numerical data summary:
data.describe()

Item_Weight  ...  Item_Outlet_Sales
count  11765.000000  ...        8523.000000
mean      12.792854  ...        2181.288914
std        4.652502  ...        1706.499616
min        4.555000  ...          33.290000
25%        8.710000  ...         834.247400
50%       12.600000  ...        1794.331000
75%       16.750000  ...        3101.296400
max       21.350000  ...       13086.964800

[8 rows x 5 columns]

# Data Cleaning

In [7]:
#Check missing values:
data.apply(lambda x: sum(x.isnull()))

Item_Identifier                 0
Item_Weight                  2439
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales            5681
source                          0
dtype: int64

### Filling missing values

In [8]:
data.Item_Outlet_Sales = data.Item_Outlet_Sales.fillna(data.Item_Outlet_Sales.mean())

In [9]:
data.Item_Weight = data.Item_Weight.fillna(data.Item_Weight.mean())

In [10]:
data['Outlet_Size'].value_counts()

Medium    4655
Small     3980
High      1553
Name: Outlet_Size, dtype: int64

In [11]:
data.Outlet_Size = data.Outlet_Size.fillna('Medium')

In [12]:
data.apply(lambda x: sum(x.isnull()))

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
source                       0
dtype: int64

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14204 entries, 0 to 14203
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Item_Identifier            14204 non-null  object 
 1   Item_Weight                14204 non-null  float64
 2   Item_Fat_Content           14204 non-null  object 
 3   Item_Visibility            14204 non-null  float64
 4   Item_Type                  14204 non-null  object 
 5   Item_MRP                   14204 non-null  float64
 6   Outlet_Identifier          14204 non-null  object 
 7   Outlet_Establishment_Year  14204 non-null  int64  
 8   Outlet_Size                14204 non-null  object 
 9   Outlet_Location_Type       14204 non-null  object 
 10  Outlet_Type                14204 non-null  object 
 11  Item_Outlet_Sales          14204 non-null  float64
 12  source                     14204 non-null  object 
dtypes: float64(4), int64(1), object(8)
memory usag

In [14]:
#Item type combine:
data['Item_Identifier'].value_counts()
data['Item_Type_Combined'] = data['Item_Identifier'].apply(lambda x: x[0:2])
data['Item_Type_Combined'] = data['Item_Type_Combined'].map({'FD':'Food',
                                                             'NC':'Non-Consumable',
                                                             'DR':'Drinks'})
data['Item_Type_Combined'].value_counts()

Food              10201
Non-Consumable     2686
Drinks             1317
Name: Item_Type_Combined, dtype: int64

### Numerical and One-Hot Coding of Categorical variables

In [15]:
#Import library:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le = LabelEncoder()
#New variable for outlet
data['Outlet'] = le.fit_transform(data['Outlet_Identifier'])
var_mod = ['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Item_Type_Combined','Outlet_Type','Outlet']
le = LabelEncoder()
for i in var_mod:
    data[i] = le.fit_transform(data[i])

In [16]:
#One Hot Coding:
data = pd.get_dummies(data, columns=['Item_Fat_Content','Outlet_Location_Type','Outlet_Size','Outlet_Type','Item_Type_Combined','Outlet'])

In [31]:
data.head()

Item_Identifier  Item_Weight  Item_Visibility  ...  Outlet_7 Outlet_8  Outlet_9
0           FDA15         9.30         0.016047  ...         0        0         1
1           DRC01         5.92         0.019278  ...         0        0         0
2           FDN15        17.50         0.016760  ...         0        0         1
3           FDX07        19.20         0.000000  ...         0        0         0
4           NCD19         8.93         0.000000  ...         0        0         0

[5 rows x 35 columns]

In [18]:
data.dtypes

Item_Identifier               object
Item_Weight                  float64
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Item_Outlet_Sales            float64
source                        object
Item_Fat_Content_0             uint8
Item_Fat_Content_1             uint8
Item_Fat_Content_2             uint8
Item_Fat_Content_3             uint8
Item_Fat_Content_4             uint8
Outlet_Location_Type_0         uint8
Outlet_Location_Type_1         uint8
Outlet_Location_Type_2         uint8
Outlet_Size_0                  uint8
Outlet_Size_1                  uint8
Outlet_Size_2                  uint8
Outlet_Type_0                  uint8
Outlet_Type_1                  uint8
Outlet_Type_2                  uint8
Outlet_Type_3                  uint8
Item_Type_Combined_0           uint8
Item_Type_Combined_1           uint8
Item_Type_Combined_2           uint8
O

### Exporting Data

In [19]:
import warnings
warnings.filterwarnings('ignore')
#Drop the columns which have been converted to different types:
data.drop(['Item_Type','Outlet_Establishment_Year'],axis=1,inplace=True)

#Divide into test and train:
train = data.loc[data['source']=="train"]
test = data.loc[data['source']=="test"]

#Drop unnecessary columns:
test.drop(['Item_Outlet_Sales','source'],axis=1,inplace=True)
train.drop(['source'],axis=1,inplace=True)

#Export files as modified versions:
train.to_csv("train_modified.csv",index=False)
test.to_csv("test_modified.csv",index=False)

# Model Building

In [20]:
# Reading modified data
train2 = pd.read_csv("train_modified.csv")
test2 = pd.read_csv("test_modified.csv")

In [21]:
train2.head()

Item_Identifier  Item_Weight  Item_Visibility  ...  Outlet_7 Outlet_8  Outlet_9
0           FDA15         9.30         0.016047  ...         0        0         1
1           DRC01         5.92         0.019278  ...         0        0         0
2           FDN15        17.50         0.016760  ...         0        0         1
3           FDX07        19.20         0.000000  ...         0        0         0
4           NCD19         8.93         0.000000  ...         0        0         0

[5 rows x 34 columns]

In [22]:
X_train = train2.drop(['Item_Outlet_Sales', 'Outlet_Identifier','Item_Identifier'], axis=1)
y_train = train2.Item_Outlet_Sales

In [23]:
X_test = test2.drop(['Outlet_Identifier','Item_Identifier'], axis=1)

In [24]:
X_train.head()

Item_Weight  Item_Visibility  Item_MRP  ...  Outlet_7  Outlet_8  Outlet_9
0         9.30         0.016047  249.8092  ...         0         0         1
1         5.92         0.019278   48.2692  ...         0         0         0
2        17.50         0.016760  141.6180  ...         0         0         1
3        19.20         0.000000  182.0950  ...         0         0         0
4         8.93         0.000000   53.8614  ...         0         0         0

[5 rows x 31 columns]

In [25]:
y_train.head()

0    3735.1380
1     443.4228
2    2097.2700
3     732.3800
4     994.7052
Name: Item_Outlet_Sales, dtype: float64

## Linear Regression Model:

In [54]:
# Fitting Multiple Linear Regression to the training set
from sklearn.linear_model import  LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [55]:
# Predicting the test set results
y_pred = regressor.predict(X_test)

In [56]:
y_pred

array([1848.53604783, 1472.81670435, 1875.65285894, ..., 1809.18796433,
       3565.6645235 , 1267.46171871])

In [57]:
lr_accuracy = round(regressor.score(X_train,y_train) * 100,2)
lr_accuracy

56.36

In [58]:
r2_score(y_train, regressor.predict(X_train))

0.563589277727048

In [61]:
print("RMSE : %.4g" % np.sqrt(mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1127


In [62]:
submission = pd.DataFrame({
'Item_Identifier':test2['Item_Identifier'],
'Outlet_Identifier':test2['Outlet_Identifier'],
'Item_Outlet_Sales': y_pred
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [63]:
submission.to_csv('submission1.csv',index=False)

## Decision Tree Model:

In [64]:
# Fitting Decision Tree Regression to the dataset
from sklearn.tree import DecisionTreeRegressor
regressor = DecisionTreeRegressor(max_depth=15,min_samples_leaf=300)
regressor.fit(X_train, y_train)


DecisionTreeRegressor(max_depth=15, min_samples_leaf=300)

In [65]:
# Predicting the test set results
y_pred = regressor.predict(X_test)
y_pred

array([1673.98398729, 1349.51290433,  471.30684669, ..., 1892.06614452,
       3805.94860417, 1349.51290433])

In [66]:
tree_accuracy = round(regressor.score(X_train,y_train),2)
tree_accuracy

0.59

In [67]:
r2_score(y_train, regressor.predict(X_train))

0.5884050821570486

In [69]:
print("RMSE : %.4g" % np.sqrt(mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1095


In [70]:
submission = pd.DataFrame({
'Item_Identifier':test2['Item_Identifier'],
'Outlet_Identifier':test2['Outlet_Identifier'],
'Item_Outlet_Sales': y_pred
},columns=['Item_Identifier','Outlet_Identifier','Item_Outlet_Sales'])

In [71]:
submission.to_csv('submission2.csv',index=False)

## Random Forest Model:

In [72]:
# Fitting Random Forest Regression to the dataset
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=100,max_depth=6, min_samples_leaf=50,n_jobs=4)
regressor.fit(X_train, y_train)

RandomForestRegressor(max_depth=6, min_samples_leaf=50, n_jobs=4)

In [73]:
# Predicting the test set results
y_pred = regressor.predict(X_test)
y_pred

array([1648.5740568 , 1371.98044998,  592.41903813, ..., 1956.17950749,
       3734.92339518, 1307.26466159])

In [74]:
rf_accuracy = round(regressor.score(X_train,y_train),2)
rf_accuracy

0.61

In [75]:
r2_score(y_train, regressor.predict(X_train))

0.6125592721726949

In [76]:
print("RMSE : %.4g" % np.sqrt(mean_squared_error(y_train, regressor.predict(X_train))))

RMSE : 1062
